# Generated by Django 5.2.12 on 2026-04-01 21:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_students', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='exam_schedules', to='allocation.classroom')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'ordering': ['date', 'start_time'],
                'unique_together': {('course_name', 'date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('PROF', 'Professor'), ('ASSOC', 'Associate Professor'), ('ASST', 'Assistant Professor')], default='ASST', max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('duty_quota', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PhDScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_duties', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phdscholar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhD Scholar',
                'verbose_name_plural': 'PhD Scholars',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DutyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('FACULTY', 'Faculty'), ('PHD', 'PhD Scholar')], default='FACULTY', max_length=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_allocations', to='allocation.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_allocations', to='allocation.examschedule')),
            ],
            options={
                'verbose_name': 'Duty Allocation',
                'verbose_name_plural': 'Duty Allocations',
                'ordering': ['exam', 'classroom'],
                'unique_together': {('exam', 'classroom', 'assigned_to')},
            },
        ),
        migrations.CreateModel(
            name='SeatingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_roll', models.PositiveIntegerField()),
                ('end_roll', models.PositiveIntegerField()),
                ('capacity_used', models.PositiveIntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_allocations', to='allocation.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_allocations', to='allocation.examschedule')),
            ],
            options={
                'verbose_name': 'Seating Allocation',
                'verbose_name_plural': 'Seating Allocations',
                'ordering': ['exam', 'classroom'],
                'unique_together': {('exam', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='UFMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufm_records', to='allocation.examschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufm_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UFM Record',
                'verbose_name_plural': 'UFM Records',
                'ordering': ['-last_updated'],
                'unique_together': {('exam', 'user')},
            },
        ),
    ]
