# Generated by Django 5.2.12 on 2026-03-11 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhDScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('max_duties', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_students', models.PositiveIntegerField(default=0)),
                ('classrooms', models.ManyToManyField(related_name='exam_schedules', to='allocation.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(choices=[('PROF', 'Professor'), ('ASSOC', 'Associate Professor'), ('ASST', 'Assistant Professor')], default='ASST', max_length=50)),
                ('duty_quota', models.IntegerField(default=5)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhD_Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_duties', models.IntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DutyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='allocation.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='allocation.examschedule')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='allocation.faculty')),
                ('phd_scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='allocation.phdscholar')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_roll', models.PositiveIntegerField()),
                ('end_roll', models.PositiveIntegerField()),
                ('capacity_used', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_allocations', to='allocation.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_allocations', to='allocation.examschedule')),
            ],
        ),
        migrations.CreateModel(
            name='UFMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.examschedule')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.faculty')),
                ('phd_scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.phdscholar')),
            ],
            options={
                'unique_together': {('exam', 'faculty', 'phd_scholar')},
            },
        ),
    ]
